import { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowRight,
  CheckCircle2,
  ClipboardCopy,
  Cpu,
  GitBranch,
  MonitorSmartphone,
  TerminalSquare,
  ChevronRight,
} from 'lucide-react';
import { PUBLIC_ROUTES, getAppPath } from '../lib/routes';

/* ------------------------------------------------------------------ */
/*  Reusable code block with copy button                              */
/* ------------------------------------------------------------------ */

function CodeBlock({ title, language, children }: { title?: string; language?: string; children: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(children.trim());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative rounded-xl border border-slate-200 bg-[#f8fafc] overflow-hidden">
      {(title || language) && (
        <div className="flex items-center justify-between border-b border-slate-200 bg-white px-4 py-2">
          <span className="text-xs font-medium text-slate-500">{title || language}</span>
          <button
            onClick={handleCopy}
            className="inline-flex items-center gap-1 rounded-lg px-2 py-1 text-xs text-slate-500 hover:bg-slate-100 hover:text-slate-700 transition-colors"
          >
            <ClipboardCopy className="h-3.5 w-3.5" />
            {copied ? 'Copied!' : 'Copy'}
          </button>
        </div>
      )}
      {!title && !language && (
        <button
          onClick={handleCopy}
          className="absolute right-2 top-2 inline-flex items-center gap-1 rounded-lg bg-white/80 px-2 py-1 text-xs text-slate-500 hover:bg-white hover:text-slate-700 shadow-sm transition-colors"
        >
          <ClipboardCopy className="h-3.5 w-3.5" />
          {copied ? 'Copied!' : 'Copy'}
        </button>
      )}
      <pre className="overflow-x-auto p-4 text-sm leading-relaxed">
        <code className="font-mono text-slate-800">{children.trim()}</code>
      </pre>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  Step component                                                    */
/* ------------------------------------------------------------------ */

function Step({ number, title, children }: { number: number; title: string; children: React.ReactNode }) {
  return (
    <div className="flex gap-4">
      <div className="flex h-8 w-8 flex-none items-center justify-center rounded-full bg-indigo-600 text-sm font-bold text-white">
        {number}
      </div>
      <div className="flex-1 min-w-0">
        <h4 className="text-base font-semibold text-slate-900">{title}</h4>
        <div className="mt-2 space-y-3 text-sm leading-7 text-slate-600">{children}</div>
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  Integration path data                                             */
/* ------------------------------------------------------------------ */

const TAB_IDS = ['android', 'embedded', 'cicd', 'web'] as const;
type TabId = typeof TAB_IDS[number];

interface IntegrationPath {
  id: TabId;
  title: string;
  icon: typeof MonitorSmartphone;
  summary: string;
  architecture: string;
  steps: { title: string; content: React.ReactNode }[];
}

const paths: IntegrationPath[] = [
  {
    id: 'android',
    title: 'Android Device Testing',
    icon: MonitorSmartphone,
    summary: 'ADB-connected phones, tablets, and custom Android boards running pytest, Espresso, or UI Automator.',
    architecture:
      'Host machine (Linux/macOS) connects to Android devices via USB/ADB. pytest runs test suites that interact with devices through ADB commands. JUnit XML results are generated by pytest-junit-xml and pushed to TestForge via the reporter script. The TestForge agent runs as a systemd service, sending device heartbeats and auto-uploading new result files.',
    steps: [
      {
        title: 'Install the TestForge agent on the host',
        content: (
          <>
            <p>Run the one-line installer on the machine that controls your Android devices:</p>
            <CodeBlock title="bash" language="bash">{`curl -fsSL https://raw.githubusercontent.com/CandanUmut/testforge/main/scripts/install.sh | sudo bash`}</CodeBlock>
            <p>The installer will prompt for your API URL, API key, and device name. It creates a systemd service that sends heartbeats and watches for new result files.</p>
          </>
        ),
      },
      {
        title: 'Configure your pytest suite to emit JUnit XML',
        content: (
          <>
            <p>Add the <code className="rounded bg-slate-100 px-1.5 py-0.5 font-mono text-xs">--junitxml</code> flag to your pytest invocation:</p>
            <CodeBlock title="pytest.ini" language="ini">{`[pytest]
addopts = --junitxml=/opt/testforge/results/android-tests.xml
junit_family = xunit2`}</CodeBlock>
            <p>Or pass it directly on the command line:</p>
            <CodeBlock language="bash">{`pytest tests/android/ --junitxml=/opt/testforge/results/smoke.xml`}</CodeBlock>
          </>
        ),
      },
      {
        title: 'Push results manually (optional)',
        content: (
          <>
            <p>If you prefer not to use the file-watcher agent, push results directly:</p>
            <CodeBlock language="bash">{`python3 /opt/testforge/agent/testforge_reporter.py \\
    --url https://your-project.supabase.co \\
    --api-key tf_xxxxxxxxxxxx \\
    --junit-xml /opt/testforge/results/smoke.xml \\
    --device-name DUT-A001 \\
    --suite-name post-flash-smoke \\
    --firmware-version v3.2.1`}</CodeBlock>
          </>
        ),
      },
      {
        title: 'Verify in the dashboard',
        content: (
          <>
            <p>Open the TestForge dashboard and confirm:</p>
            <ul className="list-disc space-y-1 pl-5">
              <li>The device appears on the <strong>Devices</strong> page with an "online" status.</li>
              <li>The test run shows up under <strong>Test Runs</strong> with pass/fail counts.</li>
              <li>Any crash-like failures are grouped on the <strong>Crash Triage</strong> page.</li>
            </ul>
          </>
        ),
      },
    ],
  },
  {
    id: 'embedded',
    title: 'Embedded / Firmware Testing',
    icon: Cpu,
    summary: 'UART, SSH, JTAG, or custom board-control scripts for firmware and hardware-in-the-loop validation.',
    architecture:
      'A test host communicates with embedded targets over UART/SSH/JTAG. Test scripts (Python, Robot Framework, or shell) exercise the firmware, capture logs, and produce JUnit XML. The reporter pushes results with firmware version metadata. Crash logs (assert traces, hard faults, watchdog resets) are auto-detected and forwarded to the Crash Triage system for fingerprinting.',
    steps: [
      {
        title: 'Install the reporter on your test host',
        content: (
          <>
            <p>The reporter only needs Python 3 and the <code className="rounded bg-slate-100 px-1.5 py-0.5 font-mono text-xs">requests</code> module:</p>
            <CodeBlock language="bash">{`pip3 install requests
curl -fsSL https://raw.githubusercontent.com/CandanUmut/testforge/main/scripts/testforge_reporter.py \\
    -o /usr/local/bin/testforge_reporter.py
chmod +x /usr/local/bin/testforge_reporter.py`}</CodeBlock>
          </>
        ),
      },
      {
        title: 'Include firmware metadata in every report',
        content: (
          <>
            <p>Always pass <code className="rounded bg-slate-100 px-1.5 py-0.5 font-mono text-xs">--firmware-version</code> so you can track regressions across builds:</p>
            <CodeBlock language="bash">{`FW_VERSION=$(cat /mnt/target/version.txt)

python3 testforge_reporter.py \\
    --url "$TESTFORGE_URL" \\
    --api-key "$TESTFORGE_API_KEY" \\
    --junit-xml results/uart-tests.xml \\
    --device-name CTRL-BOARD-07 \\
    --suite-name firmware-validation \\
    --firmware-version "$FW_VERSION"`}</CodeBlock>
          </>
        ),
      },
      {
        title: 'Forward crash logs and assert traces',
        content: (
          <>
            <p>The reporter auto-detects crash patterns in failure messages (segfault, panic, hard fault, watchdog, assert failed, etc.) and creates crash entries automatically. For the best results, include the full stack trace or assert log in your test failure output.</p>
            <p>Example pytest test that captures a UART crash:</p>
            <CodeBlock title="test_firmware.py" language="python">{`def test_boot_sequence(uart_connection):
    uart_connection.send("reboot\\n")
    output = uart_connection.read_until("Ready", timeout=30)
    # If the device hard-faults, the output will contain
    # "Hard Fault" or "assert failed" — the reporter will
    # detect this and create a crash entry automatically.
    assert "Ready" in output, f"Boot failed: {output}"`}</CodeBlock>
          </>
        ),
      },
      {
        title: 'Monitor device health with heartbeats',
        content: (
          <>
            <p>Send periodic heartbeats to track which boards are online:</p>
            <CodeBlock language="bash">{`# Cron job every 5 minutes
*/5 * * * * python3 /usr/local/bin/testforge_reporter.py \\
    --url "$TESTFORGE_URL" --api-key "$TESTFORGE_API_KEY" \\
    --heartbeat --device-name CTRL-BOARD-07 \\
    --firmware-version "$FW_VERSION"`}</CodeBlock>
          </>
        ),
      },
    ],
  },
  {
    id: 'cicd',
    title: 'CI/CD Pipeline',
    icon: GitBranch,
    summary: 'GitHub Actions, Jenkins, GitLab CI, or any runner that can execute Python.',
    architecture:
      'The CI runner checks out code, runs tests, and produces JUnit XML. A post-test step calls the TestForge reporter to push results. API credentials are stored as CI secrets. The reporter automatically detects crashes from failure messages and reports them. No persistent agent is needed — each CI run is a one-shot push.',
    steps: [
      {
        title: 'Store credentials as CI secrets',
        content: (
          <>
            <p>Add these secrets to your CI environment:</p>
            <ul className="list-disc space-y-1 pl-5">
              <li><code className="rounded bg-slate-100 px-1.5 py-0.5 font-mono text-xs">TESTFORGE_URL</code> — your Supabase project URL</li>
              <li><code className="rounded bg-slate-100 px-1.5 py-0.5 font-mono text-xs">TESTFORGE_API_KEY</code> — your API key (starts with <code className="font-mono">tf_</code>)</li>
            </ul>
          </>
        ),
      },
      {
        title: 'Add a GitHub Actions workflow step',
        content: (
          <>
            <CodeBlock title=".github/workflows/test.yml" language="yaml">{`name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: pytest --junitxml=results.xml

      - name: Push results to TestForge
        if: always()
        run: |
          pip install requests
          curl -fsSL https://raw.githubusercontent.com/CandanUmut/testforge/main/scripts/testforge_reporter.py -o reporter.py
          python reporter.py \\
            --url "\${{ secrets.TESTFORGE_URL }}" \\
            --api-key "\${{ secrets.TESTFORGE_API_KEY }}" \\
            --junit-xml results.xml \\
            --device-name "github-runner" \\
            --suite-name "\${{ github.repository }}" \\
            --firmware-version "\${{ github.sha }}"`}</CodeBlock>
          </>
        ),
      },
      {
        title: 'Jenkins pipeline example',
        content: (
          <>
            <CodeBlock title="Jenkinsfile" language="groovy">{`pipeline {
    agent any
    environment {
        TESTFORGE_URL     = credentials('testforge-url')
        TESTFORGE_API_KEY = credentials('testforge-api-key')
    }
    stages {
        stage('Test') {
            steps {
                sh 'pytest --junitxml=results.xml'
            }
            post {
                always {
                    sh """
                        pip install requests
                        python testforge_reporter.py \\
                            --url "\$TESTFORGE_URL" \\
                            --api-key "\$TESTFORGE_API_KEY" \\
                            --junit-xml results.xml \\
                            --device-name "jenkins-\${NODE_NAME}" \\
                            --suite-name "\${JOB_NAME}"
                    """
                }
            }
        }
    }
}`}</CodeBlock>
          </>
        ),
      },
      {
        title: 'Verify in the dashboard',
        content: (
          <>
            <p>After the CI run completes, check the TestForge dashboard to see:</p>
            <ul className="list-disc space-y-1 pl-5">
              <li>A new test run with the commit SHA as the firmware version.</li>
              <li>Trend charts comparing pass rates across branches.</li>
              <li>Crash entries if any test failures matched crash patterns.</li>
            </ul>
          </>
        ),
      },
    ],
  },
  {
    id: 'web',
    title: 'Web / API Testing',
    icon: TerminalSquare,
    summary: 'Playwright, Cypress, Jest, pytest, Robot Framework, and custom test runners.',
    architecture:
      'Your existing test framework runs as normal and produces JUnit XML output. The TestForge reporter reads the XML and pushes results via the REST API. No code changes to your tests are needed — just add a post-test step. Works with any framework that can export JUnit XML.',
    steps: [
      {
        title: 'Configure JUnit XML output for your framework',
        content: (
          <>
            <p>Most frameworks support JUnit XML natively or via a plugin:</p>
            <CodeBlock title="Playwright" language="typescript">{`// playwright.config.ts
export default defineConfig({
  reporter: [
    ['junit', { outputFile: 'results/playwright.xml' }],
    ['html'],
  ],
});`}</CodeBlock>
            <CodeBlock title="Jest" language="json">{`// package.json (or jest.config.js)
{
  "jest": {
    "reporters": [
      "default",
      ["jest-junit", { "outputDirectory": "results", "outputName": "jest.xml" }]
    ]
  }
}`}</CodeBlock>
            <CodeBlock title="pytest" language="bash">{`pytest --junitxml=results/pytest.xml`}</CodeBlock>
          </>
        ),
      },
      {
        title: 'Push results after each test run',
        content: (
          <>
            <CodeBlock language="bash">{`python3 testforge_reporter.py \\
    --url https://your-project.supabase.co \\
    --api-key tf_xxxxxxxxxxxx \\
    --junit-xml results/playwright.xml \\
    --device-name "staging-server" \\
    --suite-name "e2e-playwright" \\
    --firmware-version "$(git rev-parse --short HEAD)"`}</CodeBlock>
          </>
        ),
      },
      {
        title: 'Use environment variables for cleaner scripts',
        content: (
          <>
            <p>Set connection details once and keep your commands short:</p>
            <CodeBlock language="bash">{`export TESTFORGE_URL=https://your-project.supabase.co
export TESTFORGE_API_KEY=tf_xxxxxxxxxxxx

# Now just specify the test-specific flags
python3 testforge_reporter.py \\
    --junit-xml results/playwright.xml \\
    --device-name "staging-server" \\
    --suite-name "e2e-playwright"`}</CodeBlock>
          </>
        ),
      },
      {
        title: 'Track regressions across branches',
        content: (
          <>
            <p>Use the dashboard trends to compare test results across branches and catch regressions early. Each push includes the firmware/build version, so you can pinpoint exactly which commit introduced a failure.</p>
            <ul className="list-disc space-y-1 pl-5">
              <li>Filter test runs by suite name to focus on specific test types.</li>
              <li>Use the device view to compare results across environments (staging, production, etc.).</li>
              <li>Set up alert rules to get notified when pass rates drop below a threshold.</li>
            </ul>
          </>
        ),
      },
    ],
  },
];

/* ------------------------------------------------------------------ */
/*  Tab button                                                        */
/* ------------------------------------------------------------------ */

function TabButton({
  active,
  icon: Icon,
  label,
  onClick,
}: {
  active: boolean;
  icon: typeof MonitorSmartphone;
  label: string;
  onClick: () => void;
}) {
  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-medium transition-all ${
        active
          ? 'bg-indigo-600 text-white shadow-sm'
          : 'bg-white text-slate-600 hover:bg-slate-50 hover:text-slate-900 border border-slate-200'
      }`}
    >
      <Icon className="h-4 w-4" />
      <span className="hidden sm:inline">{label}</span>
    </button>
  );
}

/* ------------------------------------------------------------------ */
/*  Main component                                                    */
/* ------------------------------------------------------------------ */

export function SetupGuide() {
  const [activeTab, setActiveTab] = useState<TabId>('android');
  const activePath = paths.find((p) => p.id === activeTab)!;

  return (
    <div className="min-h-screen bg-white text-slate-900">
      {/* Hero section */}
      <div className="border-b border-slate-100 bg-white">
        <div className="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:px-8">
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-indigo-600">
            Setup Guide
          </p>
          <h1 className="mt-4 text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">
            Integrate TestForge in minutes.
          </h1>
          <p className="mt-5 max-w-2xl text-lg leading-8 text-slate-500">
            Keep your existing test framework. Add a single post-test step to push results,
            crash data, and device heartbeats into one unified dashboard.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <Link
              to={PUBLIC_ROUTES.apiDocs}
              className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-medium text-white hover:bg-indigo-700 transition-colors"
            >
              API Reference
              <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              to={getAppPath('demo')}
              className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-medium text-slate-700 hover:bg-slate-50 transition-colors"
            >
              Open Demo Dashboard
            </Link>
          </div>
        </div>
      </div>

      {/* Quick install banner */}
      <div className="border-b border-slate-100 bg-slate-50/50">
        <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
          <h2 className="text-sm font-semibold uppercase tracking-[0.15em] text-slate-400">
            Quick Install
          </h2>
          <div className="mt-3">
            <CodeBlock title="One-line installer (Linux)" language="bash">
              {`curl -fsSL https://raw.githubusercontent.com/CandanUmut/testforge/main/scripts/install.sh | sudo bash`}
            </CodeBlock>
          </div>
          <p className="mt-3 text-sm text-slate-500">
            Installs the reporter script, background agent, and systemd service. Requires Python 3 and pip.
          </p>
        </div>
      </div>

      {/* Integration paths */}
      <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-950">
          Choose your integration path
        </h2>
        <p className="mt-2 text-sm text-slate-500">
          Select your testing setup below for tailored instructions.
        </p>

        {/* Tabs */}
        <div className="mt-6 flex flex-wrap gap-2">
          {paths.map((p) => (
            <TabButton
              key={p.id}
              active={activeTab === p.id}
              icon={p.icon}
              label={p.title}
              onClick={() => setActiveTab(p.id)}
            />
          ))}
        </div>

        {/* Active path content */}
        <div className="mt-8 rounded-2xl border border-slate-200 bg-white">
          {/* Header */}
          <div className="border-b border-slate-100 p-8">
            <div className="flex items-start gap-4">
              <div className="flex h-12 w-12 flex-none items-center justify-center rounded-xl bg-indigo-50 text-indigo-600">
                <activePath.icon className="h-6 w-6" />
              </div>
              <div>
                <h3 className="text-xl font-semibold text-slate-950">{activePath.title}</h3>
                <p className="mt-1 text-sm leading-7 text-slate-500">{activePath.summary}</p>
              </div>
            </div>
          </div>

          {/* Architecture */}
          <div className="border-b border-slate-100 p-8">
            <h4 className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-400">
              Architecture Overview
            </h4>
            <p className="mt-3 text-sm leading-7 text-slate-600">{activePath.architecture}</p>
          </div>

          {/* Steps */}
          <div className="space-y-8 p-8">
            {activePath.steps.map((step, i) => (
              <Step key={i} number={i + 1} title={step.title}>
                {step.content}
              </Step>
            ))}
          </div>
        </div>

        {/* Bottom checklist */}
        <div className="mt-12 rounded-2xl border border-slate-200 bg-white p-8">
          <h3 className="text-lg font-semibold text-slate-950">Integration Checklist</h3>
          <p className="mt-1 text-sm text-slate-500">
            Confirm these items after setup to make sure everything is working.
          </p>
          <div className="mt-6 grid gap-3 sm:grid-cols-2">
            {[
              'Reporter script installed and reachable',
              'API key and URL configured (env vars or config file)',
              'Test framework exporting JUnit XML',
              'Test run visible in the dashboard',
              'Device heartbeat showing "online"',
              'Crash-like failures appear in Crash Triage',
              'Alert rules configured for your team',
              'CI pipeline includes the reporter step',
            ].map((item) => (
              <div key={item} className="flex items-start gap-3 rounded-xl border border-slate-100 bg-slate-50/50 p-3">
                <CheckCircle2 className="mt-0.5 h-4 w-4 flex-none text-indigo-600" />
                <span className="text-sm text-slate-700">{item}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Next steps */}
        <div className="mt-8 flex flex-wrap gap-4">
          <Link
            to={PUBLIC_ROUTES.apiDocs}
            className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-medium text-white hover:bg-indigo-700 transition-colors"
          >
            Read the full API docs
            <ChevronRight className="h-4 w-4" />
          </Link>
          <Link
            to={getAppPath('demo')}
            className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-medium text-slate-700 hover:bg-slate-50 transition-colors"
          >
            Explore the demo dashboard
            <ChevronRight className="h-4 w-4" />
          </Link>
        </div>
      </div>
    </div>
  );
}
